name: TerryStorch
favicon: null
layout_spectrum: 0.8138064534869045
typography_spectrum: 0.731141404248774
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3506213657092303
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0.2349926105234772
purpose: []
